namespace: 'backstage'
service:
  apiVersion: 'v1'
  name: 'backstage'
  port: '80'
  targetPort: 'http'

deployment:
  apiVersion: 'apps/v1'
  name: 'backstage'
  replicas: '1'

image:
  registry: 'localhost:5001'
  repository: 'backstage'
  tag: '0.1.0'

container:
  name: 'backstage'
  port: '7007'

secrets:
  backstage: 'backstage-secrets'
  postgres: 'postgres-secrets'
  ghToken: 'dummy'
  backendUrl: 'https://kubin-kloud-ominous-space-guide-q7pv6rggp64hvp-8000.preview.app.github.dev'

postgres:
  host: 'cG9zdGdyZXMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw='
  port: 'NTQzMg=='
  username: 'YmFja3N0YWdl'
  password: 'aHVudGVyMg=='
