# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backstage }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.ghToken }}
  AZURE_TOKEN: {{ .Values.secrets.azToken }}
  BACKEND_URL: {{ .Values.secrets.backendUrl }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_SERVICE_HOST: {{ .Values.postgres.host }}
  POSTGRES_SERVICE_PORT: {{ .Values.postgres.port }}
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}